# Generated by Django 5.1.6 on 2025-03-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_remove_destination_activities_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(upload_to='events/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='destinations.destination')),
            ],
        ),
    ]
