# Generated by Django 5.1.6 on 2025-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Autumn', 'Autumn')], max_length=20),
        ),
    ]
