# Generated by Django 5.1.6 on 2025-04-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_activity_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='season',
            field=models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Winter', 'Winter')], max_length=20),
        ),
    ]
