# Generated by Django 5.1.6 on 2025-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_alter_activity_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('Spring', 'Spring'), ('Autumn', 'Autumn')], max_length=10),
        ),
    ]
