# Generated by Django 5.1.6 on 2025-04-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_alter_destination_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=10),
        ),
    ]
