# Generated by Django 5.1.6 on 2025-04-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_alter_activity_season_alter_destination_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='destination',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
