# Generated by Django 5.1.6 on 2025-05-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0009_destinationphoto_photocomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocomment',
            options={'ordering': ['created_at']},
        ),
    ]
