# Generated by Django 5.1.6 on 2025-06-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_alter_photocomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocomment',
            options={},
        ),
    ]
