# Generated by Django 5.1.6 on 2025-06-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photocomment',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photocomment',
            name='user',
        ),
        migrations.AddField(
            model_name='destination',
            name='featured_on_homepage',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='DestinationPhoto',
        ),
        migrations.DeleteModel(
            name='PhotoComment',
        ),
    ]
