# Generated by Django 5.1.6 on 2025-06-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0013_remove_photocomment_photo_remove_photocomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='travel_type',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Cultural', 'Cultural'), ('Relaxation', 'Relaxation'), ('Nature', 'Nature')], default='Nature', max_length=50),
        ),
    ]
