# Generated by Django 5.1.6 on 2025-06-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0014_destination_travel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('Adventure', 'Adventure'), ('Leisure', 'Leisure'), ('Cultural', 'Cultural'), ('Nature', 'Nature'), ('Family', 'Family'), ('Romantic', 'Romantic')], max_length=100, null=True),
        ),
    ]
