# Generated by Django 5.1.6 on 2025-03-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_phone_number_customuser_age_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
