# Generated by Django 5.1.6 on 2025-04-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_remove_event_destination_delete_activity_and_more'),
        ('events', '0002_alter_event_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='destinations.destination'),
        ),
    ]
