# Generated by Django 5.1.6 on 2025-03-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Winter', 'Winter')], max_length=20)),
                ('activity_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('discount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
