# Generated by Django 5.1.6 on 2025-04-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_season_activityreview'),
        ('destinations', '0008_remove_event_destination_delete_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityreview',
            old_name='comment',
            new_name='review_text',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.AlterField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activityreview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
