# Generated by Django 5.1.6 on 2025-04-28 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
