# Generated by Django 5.1.6 on 2025-05-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_end_date_activity_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityreview',
            old_name='review_text',
            new_name='comment',
        ),
    ]
