# Generated by Django 5.1.6 on 2025-06-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_review_text_activityreview_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityReview',
        ),
    ]
