# Generated by Django 5.1.6 on 2025-06-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0011_alter_photocomment_options'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('Ocean', 'Ocean'), ('Summer', 'Summer'), ('Sport', 'Sport')], max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
