# Generated by Django 5.1.6 on 2025-06-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedtrip',
            old_name='shared',
            new_name='favorite',
        ),
    ]
