# Generated by Django 5.1.6 on 2025-06-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_rename_shared_savedtrip_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtrip',
            name='accommodation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='shared',
            field=models.BooleanField(default=False, help_text='Make this trip public'),
        ),
    ]
