# Generated by Django 5.1.6 on 2025-06-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_savedtrip_accommodation_savedtrip_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtrip',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Cultural', 'Cultural'), ('Romantic', 'Romantic'), ('Family', 'Family'), ('Other', 'Other')], default='Adventure', max_length=50),
        ),
    ]
