# Generated by Django 5.1.6 on 2025-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_hotelbooking_user_tourbooking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourbooking',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='number_of_persons',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='travel_date',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='persons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='booking_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='category',
            field=models.IntegerField(choices=[(1, 'Kids'), (2, '1'), (3, '2'), (4, '3')]),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='destination',
            field=models.IntegerField(choices=[(1, 'Destination 1'), (2, 'Destination 2'), (3, 'Destination 3')]),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='special_request',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
