# Generated by Django 5.1.6 on 2025-04-30 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_full_name_tourbooking_name_and_more'),
        ('destinations', '0008_remove_event_destination_delete_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='category',
            field=models.IntegerField(choices=[(1, 'Kids'), (2, 'Adults'), (3, 'Family'), (4, 'Group')]),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
        ),
    ]
