# Generated by Django 5.1.6 on 2025-05-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_tourbooking_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
